---
title: "Digital economy in the UK: a multi-scalar story of the diffusion of web technologies"
author:
  - name: Emmanouil Tranos
    email: e.tranos@bristol.ac.uk
    affiliations: 
      - id: some-tech
        name: University of Bristol and The Alan Turing Institute
        department: 
        address: 
        city: 
        state: State
        postal-code: UK
    corresponding: e.tranos@bristol.ac.uk
address:
  - attributes:
        corresponding: true
    note: This is the first author footnote.
abstract: |
  This paper maps the participation in the digital economy and its evolution in the UK over space and time. Most of the existing economic geography literature which dealt with the spatiality of the internet employed supply-side measures, such as infrastructural capacity, in order to understand the geography of the digital economy and its potential spatial economic effects. Useful as these approaches might have been, they cannot capture the micro-processes and the characteristics of the individual online behaviour. Using large volumes of archived and geolocated web content, this paper models the diffusion of web technologies over space and time in the UK. The data and geolocation strategy allow to capture these processes at a very granular spatial scale. The modelling approach, which is based on simple spatial analytical methods and on the estimation of diffusion curves at various scales, enables to depict the role of geography and other cognitive factors which drove the diffusion of web technologies. Although the focus is on a recent historical period -- 1996-2012 -- the results of the analysis depict diffusion mechanisms which can be very useful in understanding the evolutionary patterns of the adoption of other newer technologies.
keywords: 
  - keyword1
  - keyword2
date: last-modified
bibliography: bibliography.bib
format:
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Journal Name
      formatting: preprint
      model: 3p
      cite-style: super
editor: 
  markdown: 
    wrap: 72
---

# Introduction {#sec:1}

Geographers were always interested in how new technologies and
innovations diffuse across space and, importantly, how such
spatio-temporal processes can be modelled. The seminal contribution of
@hagerstrand1968innovation is illustrative of this early interest.
However, the torch of exploring and modelling such processes had been
passed to other disciplines such as economics, business studies and
sociology well before the 'cultural turn' of economic geography
[@perkins2005international]. A potential explanation of lack of studies
exploring the diffusion of new and, more specifically, digital
technologies across *both* space and time can be attributed to the
scarcity of relevant and granular enough data. As @zook2022mapping
highlight, digital activities are hardly ever captured in official data.

This paper aims to reinstate geographers' interest in how new and
digital technologies diffuse over space and time. It adopts a geographic
standpoint to explore and map the diffusion of web technologies in the
UK over space and time. It does so by employing a novel source of big
data which captures the active engagement with web technologies during
the $1996-2013$ period.

The motivation for this paper lies in the fact that there are various
stakeholders who are interested in knowing how new digital technologies
diffused over space and time use this information to make predictions
regarding the diffusion of related future technologies. As per
@meade2021modelling a variety of actors have a direct interest in
gaining such knowledge including network equipment suppliers; network
operators, regulatory and local authorities. And despite the spatial
heterogeneity of such diffusion mechanisms and the policy relevance,
there are very limited attempts in the literature to analyse the
diffusion of new digital technologies at a granular level.

the paper answers an empirical question: how did a

@zook2022mapping Because new digital activities are rarely---if
ever---captured in official state data, researchers must rely on
information gathered from alternative sources. With this in mind, the
overarching aim of this article is outlining an approach for analyzing
the "new spaces and geographies" of digital phenomena and practices.

<!-- motivation -->

Classifying adopters of a technology along a time axis was pioneered by
Rogers (1962), who categorized adopters into five groups as innovators,
early adopters, early majority, late majority and laggards.

An a priori approach groups similar countries into segments, where
similarity is defined using economic, social, or political covariates.
Examples include Hofstede (2001) and Lee (1990). An a posteriori
analysis considers segments based on realized market behaviour, for
example see Sood et al. (2009). Some studies investigate changing
segment membership over time, see Cannon and Yaprak (2011).

@fritsch2015new Hägerstrand (1952, 1967) was the first scholar to
intensively analyze spatial diffusion pro cesses. Based on the empirical
observations of the regional spread of process innovations, he
hypothesized that new technology is first implemented in the 'center' --
the large agglom erations -- and then moves 'down' the spatial
hierarchy, the last stop being the 'periphery', i.e. remote and sparsely
populated regions. There are at least two factors that may explain this
pattern: first, the transfer of tacit knowledge via face-to-face contact
and second, the absorptive capacity of a region.

<!-- key concepts -->

@bento2015spatial The concept of absorptive capacity has also been
applied in the TIS context in terms of the con-struction of capacity
needed to transfer and implement a new technology in the receiving
country (cf.Van Alphen, 2011), with repercussions for the nature of
system functions

@bednarz2020pulled larger local technological niches (at least from a
demand perspective) are more likely to be formed in urban areas than in
rural ones, which is in line with the work of Ha¨gerstrand (1965a,b).
However, size is not the only regional characteristic that may matter in
this context. Regions also differ in accumulated experiences and the
presence of tacit knowledge with respect to products, as well as in
actors' propensity share this knowledge among producers (Martin et al.,
2019)

<!-- @das2022diffusion -->

<!-- Epidemic approach: The approach emphasizes that the adoption of a -->

<!-- technology spreads like an infection among the potential adopters. By -->

<!-- taking a homogeneous group of potential adopters as an assumption, it -->

<!-- explains the adoption of any innovation. -->

To summarize the discussion, first, here the diffusion process is
selfperpetuating as initial use stimulates further use. Second, it
follows a disequilibrium path as the level of users is always lower than
the number of potential users (Stoneman 2002).

The criticisms are mainly based on the fact that although the approach
gives an idea of aggregate (industry or household) behaviour, it does
not focus on the individual's (firm or household) adoption process

<!-- Rogers3, that divides adopters as: (I.) Innovators: first 2.5%, (II.) -->

<!-- Early adopters: next 13.5%, (III.) Early Majority: following 34%, (IV.) -->

<!-- Late Majority: next 34%, and the rest as (V.) Laggards -->

@morrill2020spatial Spatial diffusion is the process by which behavior
or characteristics of the landscape change as a result of what happens
elsewhere earlier. Spatial diffusion is the spread of the phenomenon,
over space and timed, from limited origins

Contagious diffusion=\> spatial autocorelation

expansion-type diffusion

<!-- the three geographic diffusion processes are (1) purely contagious where -->

<!-- distance or adjacency is the absolute controlling factor, (2) purely -->

<!-- hierarchical where size or urban position in the central place hierarchy -->

<!-- is the absolute controlling factor, or (3) where the location of change -->

<!-- is purely random. These are the pure or ideal forms of the diffusion -->

<!-- process; all real diffusion processes are the result of a combination of -->

<!-- these extremes. -->

The work by the communication sociologist Everett Rogers (1962, 1971,
1983) has emphasized the role of information, communication, formal and
informal media, opinion leaders and social networks, and economic and
psychological constraints on acceptance. Rogers's work stresses the
decision mechanism of the potential adopter; the work of Rogers
partitions the adopter's process of choosing to accept a new phenomenon
or trait into five stages: stage 1--the potential adopter gains
knowledge or awareness of an innovation; stage 2--persuasion is
exercised to adopt; stage 3--a decision is made to adopt; stage 4--the
decision to adopt is implemented; stage 5--the adopter confirms the
decision to adopt. In Rogers's stage theory there may be a substantial
time lag between when a potential adopter becomes aware of the new
characteristic and when a decision is actually made to adopt.

Hägerstrand considered diffusion to be a fundamental geographic process:
Whatever the phenomenon being diffused might be, one may consider it in
the context of a larger universal process of spatial diffusion.

<!-- @das2022diffusion [not good paper] Invention, innovation and diffusion -->

<!-- are considered as the three pillars of the theory of technological -->

<!-- change and Schumpeter is considered as the father of the study of -->

<!-- diffusion -->

@leibowicz2016representing Diffusion is a spatial (Hagerstrand, 1967) as
well as a temporal process, and historical evidence confirms that
technologies diffuse at different times, at different rates, and to
different extents in different places, and can be significantly
influenced by policies (Victor, 1993).

<!-- @leibowicz2016representing -->

<!-- An illustrative empirically based theory for technology -->

<!-- diffusion across multiple regions is suggested by "Schmidt's Law" -->

<!-- (Grubler, 1990). With respect to a specific technology, it divides -->

<!-- regions into three groups: core, rim, and periphery. The core is where -->

<!-- the technology is invented, subject to experimentation, and first -->

<!-- deployed commercially. To develop the technology, the core must have -->

<!-- both sufficient innovative ability and economic motivation to make the -->

<!-- necessary resource commitment. As the technology spreads from the core -->

<!-- to the rim and eventually to the periphery, later adopters have the -->

<!-- advantage of benefiting from the experiences of earlier adopters via -->

<!-- knowledge spillover effects (Verdolini and Galeotti, 2011). At this -->

<!-- point, the technology has likely been refined and costs have likely -->

<!-- declined significantly. Schmidt's Law claims that, as a result, -->

<!-- diffusion proceeds at a faster rate in regions which adopt the -->

<!-- technology later. However, diffusion tends to be less pervasive in -->

<!-- regions where adoption is delayed, ultimately saturating at a lower -->

<!-- extent than in regions where adoption occurred earlier. This is often -->

<!-- attributed to a lack of proper institutions and infrastructures in later -->

<!-- adopters, markets whichmay not be as favorable to a technology, or the -->

<!-- availability of yet newer options that invite technological -->

<!-- leapfrogging. -->

Lastly, it can be globally optimal for innovative economies to deploy
advanced technologies more than what is locally optimal if this enables
faster diffusion in less advanced regions that could benefit from the
technology.

wilson201281 Early on in their lifecycle, new technologies are crude,
imperfect, and expensive (Rosenberg, 1994). New energy technologies are
attractive for their ability to perform a particular task or deliver a
new or improved energy service (Fouquet, 2010). This is often
circumscribed by a particular set of needs in a particular context: a
market 'niche'. End-users in niche markets are generally less sensitive
to the effective price of the energy service provided or have a higher
willingness to pay for its performance advantages (Fouquet, 2010). Thus
initially, performance dominates cost competitiveness (Wilson and
Grubler, 2011). Market niches afford some protection from competitive
pressures, allowing technologies to be tested and improved in applied
settings, reducing uncertainties with performance or market demand (Kemp
et al., 1998). Costs may only fall substantively after an extended
period of commercial experimentation, concurrent with the establishment
of an industrial base and characteristic moves towards standardisation
and mass production (Grubler, 1998). The influence of accumulating
production experience on costs is captured by the concept of learning.

<!-- @grubler1990rise Following the definition given by Rogers, 1983, -->

<!-- diffusion is the process by which an innovation is communicated through -->

<!-- certain communication channels over time among the members of a social -->

<!-- system. An innovation may be an idea, object or practice which is -->

<!-- perceived as new by an individual or another unit of adoption (e.g., an -->

<!-- organization) . Communication via communication channels refers to how -->

<!-- knowledge about an innovation is transferred between the members of a -->

<!-- social system. Communication takes time, and is therefore an important -->

<!-- aspect of innovation diffusion. In fact, all theoretical and empirical -->

<!-- diffusion studies agree that an innovation does not instantly diffuse -->

<!-- into a social system. Instead a typical time pattern of diffusion along -->

<!-- a S-shaped trajectory seems to be the rule. The S-shaped pattern of -->

<!-- diffusion appears to be a basic anthropologic phenomenon, as it is also -->

<!-- confirmed by a large number of studies· of primitive preindustrial -->

<!-- societies. -->

grubler1990rise The scale of spatial innovation diffusion is similar to
that of temporal diffusion models: hierarchically decomposed.

<!-- grubler1990rise -->

<!-- Spatial innovation diffusion in Hagerstrand's model consists of three -->

<!-- stages. Stage 1: Local concentrations of initial acceptances (initial -->

<!-- agglomeration) . Stage 2: Radial dissemination outward from the initial -->

<!-- agglomeration, accompanied by the rise of secondary agglomerations. -->

<!-- Stage 3: The condensing and saturation stage, in which filling-in occurs -->

<!-- and diffusion eventually ceases. -->

<!-- grubler1990rise -->

<!-- Thus, three main characteristics define the spatial diffusion process: -->

<!-- (1) As in temporal diffusion models, an S-shaped pattern in the -->

<!-- cumulative level of adoption. (2) A "hierarchy effect" by which -->

<!-- diffusion proceeds from initial centers to secondary ones. Within the -->

<!-- context of urban systems (central places) this implies a hierarchical -->

<!-- spread of an innovation from larger to smaller centers, and from the -->

<!-- centers to the surrounding hinterland. (3) A "neighborhood effect" Le., -->

<!-- diffusion proceeds outwards from innovation centers, first "hitting" -->

<!-- (Brown, 1981) nearby rather than far-away locations. -->

@grubler1990rise Later Hagerstrand conceptualized physical "barrier"
effects like lakes or uninhabited areas, which, in addition to distance,
act as further retarding effects on diffusion. These are formalized in
the form of "zero" or "half" contact multiplicators on the (distance
decaying) message flows.

@grubler1990rise With respect to the formalization of the communication
flows Hagerstrand defines a "mean information field" (MIF), in which the
probability of communication is a negative function of distance between
individuals

@perkins2005international Theoretical models disagree as to why firms
adopt innovations at different times. Epidemic models emphasize
information (Griliches 1957). Certain firms are hypothesized to adopt
earlier because they come into contact with, and learn from, adopters of
the new technology before others. Economic models, on the other hand,
predominantly emphasize firm heterogeneity (Ireland and Stoneman 1986).
Firms adopt technologies at different times because they differ with
respect to various organizational and environmental variables
influencing the economic returns from adoption (Blackman 1999).

Either way, the strong assumption is that developing countries can
acquire modern technology innovated in developed economies, often at a
fraction of the original research and development (R&D) costs, thereby
leapfrogging many decades of technological progress (Teece 2000).

The first involves a country's geographical location. Recent empirical
work suggests that diffusion is ''geographically localized'' (Globerman,
Kokko, and Sjo¨holm 2000; Keller 2002; Milner 2003) in that a technology
diffuses faster in a country where it is already more widely diffused in
neighboring countries. Underlying these regional effects are contagion
and contact with prior users or producers of technology.

@ding2010modeling Rogers (1995) characterized early adopters as
knowledgeable risk takers. Griliches (1957) looked at the rate of return
for early adopters and characterized them as profit maximizers. The
geographer Hagerstrand (1967) was focusing on the character of early
adopters in the transmittal process that produces follow-on participants
in the process. Space was treated as a contiguity system with embedded
characteristics producing barrier elements to the diffusion process.

@ding2010modeling REVIEW ON Technological Diffusion

<!-- Hagerstrand (1968) was the first to demonstrate that diffusion typically -->

<!-- starts from innovative centers ('core´) and disseminates, through a -->

<!-- hierarchy of subcenters, to the periphery. This process is sequential -->

<!-- rather than simultaneous, and tends to accelerate from core to -->

<!-- periphery, where diffusion reaches a lower intensity than in the core -->

<!-- (Hagerstrand, 1968; Grubler, 1990; Morrill, 2005). A similar effect of -->

<!-- spatial acceleration has been identified in marketing research and is -->

<!-- known as the "lead-lag effect" (Peres et al., 2010). -->

@perkins2011internet Two main mechanisms are identified in the
literature to explain diffusion: (1) epidemic-type dynamics whereby
contact with previous adopters stimulates uptake as po tential adopters
learn about a new innovation; and (2) economic-type mechanisms whereby
potential users adopt a new innovation as it be comesmore profitable,
useful, or valuable, with uptake characteristically spreading as costs
be come lower, performance improves, or the po tential uses of the
innovation grow over time.

To this extent, our results contribute to a growing body of work that
has sought to caution against claims about the supposed novelty of the
Internet and the suggestion that it is somehow different.

<!-- methods -->

@wilson201281 Logistic growth describes an initial period of gradual
diffusion as a technology is introduced as a new commercial application,
moving then through a rapid, exponential growth phase, before slowing
and eventually saturating [@grubler1999dynamics]. The substitution of
incumbent technologies by new competitors leads to subsequent decline
and eventual obsolescence.

# Literature review {#sec2} MAYBE SKIP THIS??

<!-- previous studies -->

@beardsell1999spatial To characterize evolution of the computer
industry, we examine the distribution of relative employment across
cities in 1977 and how that distribution changes over time to 1992

There is no tendency of relative size distributions of urban computer
employment to collapse, go bimodal, or fully spread. Overall computers
exhibit some turbulence, with dramatic big winners and losers among
cities. In attracting or repelling an industry, urban heterogeneity is
important. Large, well educated cities near San Jose have much greater
chances of attracting high-tech employment and less of losing it

@bednarz2020pulled spatial innovation diffusion By using Bayesian
survival models with time-dependent data of wind turbine deployment and
firm foundation for 402 German regions between the years 1970 and 2015,
we show that the spatial evolution of the German wind energy industry
was more strongly influenced by local demand-- pull than local
supply--push processes.

The industry's initial locations are distributed relatively arbitrarily
and unpredictably, as their needs in terms of resources and skills are
diverse and distinct from the older existing industries (Boschma and
Lambooy, 1999). Consequently, emerging industries are characterized by
relatively high degrees of freedom in terms of location. In later
extensions of the concept, the assumption of the randomness of locations
was revised with greater importance assigned to regional conditions
(Boschma and Lambooy, 1999; Fornahl et al., 2012).

@perkins2005international analyze whether the rate at which new producer
technologies diffuse is significantly influenced by (1) latecomer
advantage and (2) engagement with the global economy via trade and
foreign investment

Indeed, precisely because of these latecomer advantages, developing
countries1 are believed to be well placed to catch up with developed
ones (Gerschenkron 1962; Abramovitz 1986).

@fritsch2015new analyze the spatial diffusion of laser technology
research in West Germany from 1960, when this technology began, until
2005.

@perkins2011internet

@lengyel2020role We see that the OSN spread almost exclusively from the
original location (the capital Budapest, with an order of magnitude more
inhabitants than the next size town) to various parts of the country in
the early phase of the life-cycle. Later, diffusion became less
mono-centric and other towns also emerged as spreaders. Our findings
support the idea that spreading initially happens to large distances and
becomes more local over time. This is illustrated and discussed later in
Figure 2I.

@PAPAGIANNIDIS2015308

@leibowicz2016representing for energy There is no generally accepted
theory that explains diffusion rate heterogeneity across technologies,
but several factors are considered important. Greater unit scale and
larger market size contribute to slower diffusion. Requirements for
interrelated technologies or complex infrastructures also hinder the
diffusion process (Grubler, 2012).

Mobile phones benefited from early deployment in recreational boats and
automobiles, where the traditional competitor was not a viable option.
In the early stages of diffusion, performance is a more important driver
of adoption than cost competitiveness. Typically, significant cost
reductions only occur once the technology reaches a deployment level
capable of supporting standardization and mass production (Wilson,
2012).

@leibowicz2016representing Empirical evidence supports the validity of
Schmidt's Law over a wide range of technologies, time periods, and
geographical contexts. A recent meta-analysis of technology up-scaling
found that diffusion accelerated moving from the core to the rim and
periphery for technologies as diverse as natural gas power, oil
refineries, and automobiles (Wilson, 2009). One historical example that
conforms particularly well to Schmidt's Law is the diffusion of coal
power in Europe (Grubler, 2012). England emerged as the core region for
coal power because it had legal and economic institutions that
incentivized scientific pursuits, domestic coal reserves, and a clear
industrial motivation to replace water power with coal. ...

@ding2010modeling model the spatial diffusion of mobile
telecommunications in China as well as its determinants. regional
socioeconomic characteristics play an important role in determining the
timing, speed, and level of mobile telecommunications diffusion in China

@bento2018time explore What determines the duration of formative phases
for energy innovations in different markets? We are interested both in
initial markets (also: core, lead, first mover, early adopter) where
formative phases prepare technologies for mass commercialization, and in
follower markets (also: periphery, lag, late adopter) where accelerated
formative phases may benefit from diffusion and spillovers.

# Materials and Methods {#sec3}

@wilson201281 growth function description in p. 86

from R: Asym/(1+exp((xmid-input)/scal)) using the terms from Wilson
k/(1 + e\^(t_0 - t)/scal)

Wilson: k(1 + e\^-b(t - t_0)) So, scal = - 1/b

The curve is symmetric\* around t_0

**minimum R2 = 95%**, see also @grubler1990rise

The literature usually uses the saturation level as the asymptote. I am
using the total number of websites as we cannot compute a rate.

Moran's I as @ding2010modeling **TODO** for t_0, diffusion speed

## Results {#sec3.1}

Hexagon density maps: reflect the spatial structure of Britain. Websites
are associated in places where people live and work.

**TODO** maps at the local authority level per firms and discuss
patterns

Neighbourhood effect: diffusion proceeds outwards from innovation
centers, first "hitting" nearby rather than far-away locations (Grubler
1990)

-   Moran's I: for OA and LAD over time **TODO** add 0s

-   LISA maps: for OA and LAD over time More and less expected clusters.
    Different scales show different results

-   Website density regressions: for OA and LAD over time **TODO** add
    0s Similar pattern

Hierarchy effect: from main centers to secondary ones -- central places

-   Gini coefficient. Almost perfect polarisation of web adoption in the
    early stages at a granular level More equally diffused at the Local
    Authority level Plateau overtime

S-shaped diffusion curves

-   S for LADs per firm and OA. **TODO**: OA per firm? fix firms over
    time.

-   Fast and slow LAs map. There is clustering

-   **TODo** check s_uk_firm_11

-   ranks: there is stability and movement

## 3.2 Case study approach {#sec3.2}

# Digital technologies and spatial structure: a global view {#sec4}

# The impact of ICT on the US and the UK spatial structures {#sec5}

# Discussion and conclusions {#sec6}

contrary to results from future studies regarding social media
[@lengyel2020role], web technologies did not exclusively spread from a
central location.

# References {#references .unnumbered}
