---
title: "Digital economy in the UK: a multi-scalar story of the diffusion of web technologies"
author:
  - name: Emmanouil Tranos
    email: e.tranos@bristol.ac.uk
    affiliations: 
      - id: some-tech
        name: University of Bristol and The Alan Turing Institute
        department: 
        address: 
        city: 
        state: State
        postal-code: UK
    corresponding: e.tranos@bristol.ac.uk
address:
  - attributes:
        corresponding: true
    note: This is the first author footnote.
abstract: |
  This paper maps the participation in the digital economy and its evolution in the UK over space and time. Most of the existing economic geography literature which dealt with the spatiality of the internet employed supply-side measures, such as infrastructural capacity, in order to understand the geography of the digital economy and its potential spatial economic effects. Useful as these approaches might have been, they cannot capture the micro-processes and the characteristics of the individual online behaviour. Using large volumes of archived and geolocated web content, this paper models the diffusion of web technologies over space and time in the UK. The data and geolocation strategy allow to capture these processes at a very granular spatial scale. The modelling approach, which is based on simple spatial analytical methods and on the estimation of diffusion curves at various scales, enables to depict the role of geography and other cognitive factors which drove the diffusion of web technologies. Although the focus is on a recent historical period -- 1996-2012 -- the results of the analysis depict diffusion mechanisms which can be very useful in understanding the evolutionary patterns of the adoption of other newer technologies.
keywords: 
  - keyword1
  - keyword2
date: last-modified
bibliography: bibliography
format:
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Journal Name
      formatting: preprint
      model: 3p
      cite-style: authoryear
editor: 
  markdown: 
    wrap: 72
---

# Introduction {#sec1}

<!-- geographers lack of interest + motivation -->
Geographers were always interested in how new technologies and
innovations diffuse across space and time and, importantly, how such
spatio-temporal processes can be modelled. After all, diffusion together 
with invention and innovation are considered the pillars of 
technological change [@das2022diffusion]. The seminal contribution of
@hagerstrand1968innovation is illustrative of this early interest.
However, the torch of exploring and modelling such processes had been
passed to other disciplines such as economics, business studies and
sociology well before the 'cultural turn' of economic geography
[@perkins2005international]. A potential explanation of the lack of 
geographical studies exploring the diffusion of new and, more 
specifically for this paper, digital technologies across *both* space 
and time can be attributed to the scarcity of relevant and granular 
enough data. As @zook2022mapping highlight, digital activities are 
hardly ever captured in official data.

<!-- contribution -->
This paper offers such a contribution: a geographical study illustrating 
how a new technology that is the web diffused over space and time 
in the UK at a high level of spatial granularity during the $1996-2012$ 
period. It does so by employing a novel source of big data which 
captures the active engagement with web technologies during that period.
By addressing this empirical question this paper exemplifies how the 
combination of data sources which escape the traditional social science
domain and adequate research methods can offer new lenses to geographical
research regarding the understanding of technological diffusion.

<!-- motivation -->
The motivation for this paper lies in the fact that there are various
stakeholders who are interested in knowing how new digital technologies
diffused over space and time and use this knowledge to make predictions
regarding the diffusion of related *future* technologies.
As per @leibowicz2016representing, historical studies agree on the fact that 
"technologies diffuse at different times, at different rates, and to
different extents in different places, and can be significantly
influenced by policies" [@victor1993]. @meade2021modelling highlight that 
a variety of actors have a direct interest in gaining such knowledge 
including network equipment suppliers; network operators, regulatory 
and local authorities. 
These processes and their effects vary a lot across scales: although
the diffusion of a new technology might not be optimal at a local level,
it might be beneficial from a global perspective as it could lead to 
faster diffusion to less advantaged places [@leibowicz2016representing]. 
Despite the spatial heterogeneity of such diffusion mechanisms and 
the policy relevance, there are very limited attempts in the literature 
to analyse the diffusion of new digital technologies at a detailed 
geographical level. 

<!-- diffusion and adoption -->
Technological diffusion, which is by definition an aggregated process, 
can be discussed in parallel with individual adoption mechanisms.
On the one hand, @rogers2010diffusion identifies early adopter of new 
technologies as 'knowledgeable risk takers' and @griliches1957 as 'profit 
maximisers' [@ding2010modeling]. Such individual agents are rewarded because 
of their attitude towards new technologies and innovations. On the other hand,
@perkins2011internet attribute diffusion to two processes: (i) epidemic-like 
mechanisms, which are governed by distance, proximity and social interactions, 
and (ii) by economic mechanisms as new innovations are adopted by users as they
become more profitable, valueable and useful.
<!-- The criticisms are mainly based on the fact that although the approach -->
<!-- gives an idea of aggregate (industry or household) behaviour, it does -->
<!-- not focus on the individual's (firm or household) adoption process -->

<!-- data and early engagement with the web -->
This paper focuses on the diffusion of the web as new technology during the $1996-2012$
period. This was an exciting period for digital technologies as it corresponds with
the commercialisation of the internet and, consequently, its almost universal 
adoption. The reader is reminded that it was only in 1994 when Netscape Navigator 
was introduced, a year before Microsoft's Internet Explorer
^[[https://www.theguardian.com/global/2015/mar/22/web-browser-came-back-haunt-microsoft](https://www.theguardian.com/global/2015/mar/22/web-browser-came-back-haunt-microsoft)].
Also, only $9$ per cent of UK's households had access to the internet in $1998$ 
[@ons2018], the web included mostly static webpages, there were no social media 
and web browsing was happening exclusively from desktop PCs as there were no 
smartphones [@tranosuk]. 
Hence, it is fair to say that the study period captures the very early stages of 
the diffusion on a new technology that is the web. 
This is key point in the lifecycle of a new technology. Firstly, during this period
new technologies are expensive, crude and imperfect [@rosenberg1994exploring; @wilson201281].
A simple comparison between Web 1.0 and Web 3.0 applications clearly illustrates this
[@tranos2020social]. During this period the performance of a new technology
is the main attraction and not the cost to access and use it [@wilson2011lessons]
There is a broader theoretical discussion in the literature regarding the motivation
behind early adoption. As summarised by @perkins2005international, on the one hand,
epidemic models highlight the role of interpersonal contacts as a way for new 
technologies to diffuse. On the other hand, economic models underline the importance
of heterogeneity. Different firms have different structures and business plans,
which define the potential economic returns of the adoption of a new technology 
and, therefore, the choice to adopt a new technology becomes an individual option.
From a broader and evolutionary perspective, initial conditions are essential for 
the creation and evolution of path-dependent technological development trajectories
[@neffke2011regions; @simmie2014new]. This argument is even more relevant when the
focus is on Information and Communication Technologies (ICT) because of the commonly
found lag between investment and economic returns as reflected in the Solow paradox 
[@acemoglu2014return; @brynjolfsson2018artificial].

Importantly, the data used here depicts the *active* engagement with the web in 
the UK as it contains all the commercial websites archived by the Internet Archive
^[[https://archive.org/](See https://archive.org/).]
that include a mention to at least one valid UK postcode in the web text. 
Websites are identified as commercial ones if they are part of the .co.uk second 
level domain (SLD). Also, the act of of creating a website is understood here as 
active engagement with the web vis-à-vis the more passive act of browsing the web 
or having an internet connection [@tranosuk]. Previous studies have focused mostly
on more passive notions of engaging with digital technologies such as internet 
adoption and internet speeds [e.g. @blank2018local; @riddlesden2014broadband]. 
More details about the data and the data generation process can be found in Section
[XX](#sec3). **ADD DATA DESCRIPTION, WHY .CO.UK**

<!-- description of the methods and results -->

<!-- contents -->


<!-- methods -->
@grubler1990rise Later Hagerstrand conceptualized physical "barrier"
effects like lakes or uninhabited areas, which, in addition to distance,
act as further retarding effects on diffusion. These are formalized in
the form of "zero" or "half" contact multiplicators on the (distance
decaying) message flows.

@grubler1990rise With respect to the formalization of the communication
flows Hagerstrand defines a "mean information field" (MIF), in which the
probability of communication is a negative function of distance between
individuals

@wilson201281 Logistic growth describes an initial period of gradual
diffusion as a technology is introduced as a new commercial application,
moving then through a rapid, exponential growth phase, before slowing
and eventually saturating [@grubler1999dynamics]. The substitution of
incumbent technologies by new competitors leads to subsequent decline
and eventual obsolescence.

# Literature review {#sec2}

<!-- key concepts -- copied from help.Rmd -->
Geographical diffusion is a synthesis of different processes. On the one hand, we 
can identify purely spatial or, in other words, contagious processes. Adjacency 
and, more broadly, distance are the key drivers of diffusion. 
This perspective draws similarities with epidemics: innovation just like pathogens 
spreads because of contagion and, consequently, proximity and exposure 
[@hivner2003facilitating]. On the other hand, we can identify hierarchical 
processes. Instead of horizontal distance-based diffusion mechanisms, the top-down 
hierarchy of urban systems drives diffusion. In reality, the synthesis of these 
two processes represents how new technologies diffuse over space and time [@morrill2020spatial].

These ideas were firstly introduced by Torsten Hägerstrand and his thesis entitled 
'Innovation Diffusion as a Spatial Process' [@hagerstrand1968innovation]. 
Hägerstrand was the first one to identify diffusion as a geographical process. 
The starting point was the idea that diffusion is based on passing information 
through social networks, which themselves tend to be defined by geography. Hence, 
he identified the 'neighbourhood' effect of how information, and consequently, 
innovation diffuse. He used agricultural innovations to test and model his ideas 
using Monte Carlo simulations. Hägerstrand also incorporated the role of hierarchy 
and how some phenomena maybe firstly adopted in larger cities and then diffuse 
to second tier ones. This is a sequential instead of a simultaneous process, which 
resembles the 'lead-lag' spatial acceleration effect in market research 
[@bento2018time; @PERES201091]. Hägerstrand is more widely known though for highlighting 
the role time plays in the diffusion of innovations: an early-pioneering period, 
a middle fast accelerating period and a final saturation one [@morrill2020spatial.

The temporal dimension was further explored by Everett Rogers and his seminal work 
on 'Diffusion of Innovations' [@rogers2010diffusion]. Rogers being a sociologist, 
his work focused not on the diffusion of innovations over space and time, but 
instead on the adoption of new technologies and innovations by individuals and the 
individual mechanisms that drive the decisions behind adoption. He identified five 
groups of individuals regarding their adoption speed: innovators, early adopters, 
early majority, late majority and laggards. Key mechanism of diffusion and adoption 
is always communication and how knowledge is transferred within a social system. 
Therefore, all approaches agree on the S-shaped diffusion and cumulative adoption 
pattern [@grubler1990rise].

Schmidt's Law empirically illustrates a similar pattern. *Core* and usually highly 
agglomerated regions is where new technologies are invented and commercially deployed 
[@grubler1990rise; grubler1990rise]. This is where the first adopters tend to be 
based. Then, technologies spread to the *rim* and eventually to the *periphery*. 
Although adoption pace might be higher when new technologies finally arrive to the 
periphery, the saturation levels there may never reach the ones in the core because 
of the lack of infrastructure or other necessary institutions [@leibowicz2016representing].
@grubler1990rise effectively summarises the three key characteristics of the spatial 
diffusion process: (i) the cumulative level of adoption follows an S-shaped pattern 
just like purely temporal models; (ii) diffusion is shaped by a hierarchy effect 
in a form of a centrifugal force: from core to periphery; and (iii) diffusion is 
also shaped by distance and a neighbourhood effect and contaminate nearby locations.

<!-- previous studies -->
The remaining of this section reviews empirical studies which analysed the diffusion 
on new technologies over space and time. Although the spatial dimension is present
in most of the following studies, the level of spatial detail is almost always 
more coarse than the one adopted here. @beardsell1999spatial studied 
the evolution of the computer industry in $317$ US metro areas during the $1977-1992$ 
period using employment data. Their analysis indicated that the relative size distribution
holds for urban computer employment and also urban heterogeneity is essential in
explaining this distribution. in a recent study, @bednarz2020pulled focused on 
wind turbines and modelled their spatial diffusion across $402$ German regions 
during $1970-2015$. Their key finding is that local demand than local supply was 
the main driving factor.

At a global scale @perkins2005international explored whther the diffusion rate of new
technologies is driven by a latecomer advantage and the engagement with the global
economy via foreign direct investments and trade. Their results illustrate that 
indeed latecomers and developing countries experience diffusion of new technologies 
more rapidly than early adopter and developed countries. At the same scale, 
@perkins2011internet explored whether the adoption of previous communication
technologies that is mail, telegrams and telephones was shaped by similar socioeconomic 
factors as the internet. Their results indicated common patterns regarding the 
drivers behind the adoption of different communication technologies.

Turning to studies that share more technological and scalar similarities with this 
paper, @ding2010modeling modelled the spatial diffusion of mobile telecommunications 
across regions in China. Their analysis indicated that socioeconomic characteristics 
are important determinants of the timing, speed and the level of mobile diffusion
within China. Using data from a Hungarian online social network, @lengyel2020role 
analysed its adoption and the churn at a very granular spatial level. Their results 
are in agreement with early theoretical and empirical contributions reviewed here:
assortativity, urban scaling and distance are the key drivers of spatial diffusion.
At a global scale @PAPAGIANNIDIS2015308 modelled the diffusion of different web
technologies technologies and practices. Interestingly, they did so by using similar,
but less extensive data as the one used here. Their analysis illustrated how the 
diffusion of different web technologies and practices follow an S-shaped pattern
as well as the different diffusion rates of the different technologies and practices.



<!-- @fritsch2015new analyze the spatial diffusion of laser technology -->
<!-- research in West Germany from 1960, when this technology began, until -->
<!-- 2005. -->
<!-- in one region  -->

<!-- @leibowicz2016representing for energy There is no generally accepted -->
<!-- theory that explains diffusion rate heterogeneity across technologies, -->
<!-- but several factors are considered important. Greater unit scale and -->
<!-- larger market size contribute to slower diffusion. Requirements for -->
<!-- interrelated technologies or complex infrastructures also hinder the -->
<!-- diffusion process (Grubler, 2012). -->

<!-- Mobile phones benefited from early deployment in recreational boats and -->
<!-- automobiles, where the traditional competitor was not a viable option. -->
<!-- In the early stages of diffusion, performance is a more important driver -->
<!-- of adoption than cost competitiveness. Typically, significant cost -->
<!-- reductions only occur once the technology reaches a deployment level -->
<!-- capable of supporting standardization and mass production (Wilson, -->
<!-- 2012). -->

<!-- @leibowicz2016representing Empirical evidence supports the validity of -->
<!-- Schmidt's Law over a wide range of technologies, time periods, and -->
<!-- geographical contexts. A recent meta-analysis of technology up-scaling -->
<!-- found that diffusion accelerated moving from the core to the rim and -->
<!-- periphery for technologies as diverse as natural gas power, oil -->
<!-- refineries, and automobiles (Wilson, 2009). One historical example that -->
<!-- conforms particularly well to Schmidt's Law is the diffusion of coal -->
<!-- power in Europe (Grubler, 2012). England emerged as the core region for -->
<!-- coal power because it had legal and economic institutions that -->
<!-- incentivized scientific pursuits, domestic coal reserves, and a clear -->
<!-- industrial motivation to replace water power with coal. ... -->

<!-- country level, not sure if needed. -->


<!-- @bento2018time explore What determines the duration of formative phases -->
<!-- for energy innovations in different markets? We are interested both in -->
<!-- initial markets (also: core, lead, first mover, early adopter) where -->
<!-- formative phases prepare technologies for mass commercialization, and in -->
<!-- follower markets (also: periphery, lag, late adopter) where accelerated -->
<!-- formative phases may benefit from diffusion and spillovers. -->




# Materials and Methods {#sec3}

<!-- from our RS paper -->
For instance, we can
approximate digital economic activities in a region by
measuring the volume of commercial webpages by considering
only .co.uk websites, which are dedicated to commercial
activities (Thelwall, 2000). Such commercial
websites are used to exchange information, support online
transactions and share opinions (Blazquez & Domenech,
2018). Although nothing prevents a UK-based company
from adopting a generic TLD such as.com and, indeed,
such cases escape our data, we do not expect that such
omissions could affect our results given the popularity of
the .uk ccTLD: UK consumers prefer to visit a .uk website
when they are searching for products or services (Hope,
2017); and anecdotal evidence indicates that during the
first half of 2000, three .co.uk domains were registered
every minute (OECD, 2001). Also, as Table 1 demonstrates,
.co.uk was the most popular SLD under the .uk
ccTLD in 2000. Hence, we use the total volume of all
the archived webpages in a region as a proxy for the level
of digitization. We start the analysis by focusing on commercial
webpages (.co.uk).

@wilson201281 growth function description in p. 86

from R: Asym/(1+exp((xmid-input)/scal)) using the terms from Wilson
k/(1 + e\^(t_0 - t)/scal)

Wilson: k(1 + e\^-b(t - t_0)) So, scal = - 1/b

The curve is symmetric\* around t_0

**minimum R2 = 95%**, see also @grubler1990rise

The literature usually uses the saturation level as the asymptote. I am
using the total number of websites as we cannot compute a rate.

Moran's I as @ding2010modeling **TODO** for t_0, diffusion speed

# Results {#sec3}


## Old ideas

Hexagon density maps: reflect the spatial structure of Britain. Websites
are associated in places where people live and work.

**TODO** maps at the local authority level per firms and discuss
patterns

Neighbourhood effect: diffusion proceeds outwards from innovation
centers, first "hitting" nearby rather than far-away locations (Grubler
1990)

-   Moran's I: for OA and LAD over time

-   LISA maps: for OA and LAD over time More and less expected clusters.
    Different scales show different results

-   Website density regressions: for OA and LAD over time **TODO** add
    0s Similar pattern

Hierarchy effect: from main centers to secondary ones -- central places

-   Gini coefficient. Almost perfect polarisation of web adoption in the
    early stages at a granular level More equally diffused at the Local
    Authority level Plateau overtime

S-shaped diffusion curves

-   S for LADs per firm and OA. 

-   Fast and slow LAs map. There is clustering

-   s_uk_firm_11

-   ranks: there is stability and movement

## New structure

1. S-shaped diffusion curves: S for LADs per firm. UK, fast/slow/examples

2. ranks: there is stability and movement

3. Neighbourhood effect: diffusion proceeds outwards from innovation
centers, first "hitting" nearby rather than far-away locations (Grubler
1990)

  -   Moran's I: for OA and LAD over time

  -   LISA maps: for OA and LAD over time More and less expected clusters.
    Different scales show different results

  -   Website density regressions: for OA and LAD over time

4. Hierarchy effect: from main centers to secondary ones -- central places

  -   Gini coefficient. Almost perfect polarisation of web adoption in the
    early stages at a granular level More equally diffused at the Local
    Authority level Plateau overtime

5. RF
  
  - ideal: (i) train RF for all years and all (1) LADs and (2) OAs with CAST
  and report metrics. (ii) train for all years and per region for (1) LADs and (2)
  OAs, and predict to the other regions. Reports predictions as region similarities


# Discussion and conclusions {#sec4}

contrary to results from future studies regarding social media
[@lengyel2020role], web technologies did not exclusively spread from a
central location.

# References {#references .unnumbered}
