---
title: "Response to editor and reviewer comments"
format: pdf
bibliography: bibliography.bib
---

\color{teal}
Thanks a lot for revising the paper, which has improved considerably (from its already high level).
Apart from the paper's still-not-perfect motivation, there are just a couple of minor things that remain
to be adapted. As for the motivation, I would (still) like to see a better argumentation for what the paper
adds to our understanding of diffusion processes, which, in my eyes, can be best achieved by discussing
some expectations of the relationship between diffusion mechanisms and the considered spatial scale.
In light of the magnitude of the required changes, I recommend minor revisions. Please see my detailed
responses to the author’s responses below.\color{blue}

Thanks again for the constructive comments and suggestions. Really appreciated!
Indeed, there is such a theoretical motivation and I agree that highlighting it
increases the value of the work. Briefly, this is the Modifiable Areal Unit 
Problem.

The below only includes the comments raised at the last round. I grouped 
together the points linked to the theoretical motivation. For clarity, the first 
round comments are in \color{teal}teal \color{blue} and my responses in 
\color{black} black \color{blue} fonts. Then, the second round comments are in 
\color{red} red \color{blue} and my responses in blue fonts. I hope the below 
address all the reviewer comments.

\color{teal}
\noindent 3. Novelty: The study needs to be more explicit about its novel contributions to understanding spatial diffusion mechanisms. Currently, the discussion is too general.
\color{black}

The novelty of the paper lies in the fact that there are hardly any studies
that analysed the role of these three spatial mechanisms in the diffusion 
of a new technology at such granular spatial scales. Importantly, the paper does 
this by adopting a long time series perspective which captures the commercial 
beginning of the Web until its maturity. The following paragraph in the 
introduction highlights this:

> This paper offers such a contribution: an economic geography study
revealing the importance of spatial mechanisms for the diffusion of a
digital technology that is the Web in the UK at a high level
of spatial granularity 
from the very early days until its maturity (1996-2012).
It specifically focuses on the diffusion of commercial websites.
It does so by employing a novel source of big data and machine learning
algorithms to model the *active* engagement with Web -- that is creating and 
maintaining instead of just browsing a website -- during that period
and tests how different spatial and temporal mechanisms shaped its
diffusion. This paper also exemplifies how the combination of data
sources and state-of-the-art research methods which escape the
traditional social science domain can offer new lenses to geographical
research regarding the understanding of technological diffusion.

\color{red}
Reply: I understand the empirical novelty of the paper, which is unquestioned. However, I miss
a deeper discussion of why it is important to understand diffusion at such a granular scale and
why existing studies' results lack such data, are “insufficient” or require this investigation at a
finer scale.
\color{blue}

See response below.

\color{teal}
\noindent 4. Motivation: The motivation for the study is unclear. The text raises several issues, but it is unclear which are specific to digital technologies and which pertain to technological diffusion more broadly.
\color{black}

There are three paragraphs in the revised introduction that highlight the 
paper's motivation. The first paragraph highlights the importance of this work 
from a stakeholder perspective. The second emphasises the importance of 
technology and its adoption in economic geography and macroeconomic growth 
theories. The third one, motivates the paper from the standpoint of digital 
geographies and connects it to that literature.

> <!-- motivation: stakeholders -->
The motivation for this paper lies in the fact that there are various
stakeholders who are interested in knowing how new digital technologies
diffuse over space and time and use this knowledge to make predictions
about the diffusion of related future technologies. As per
@leibowicz2016representing, historical studies agree that technologies
diffuse differently in terms of times, rates, and geographies and can be
driven by related policies [@victor1993]. @meade2021modelling highlight
that a variety of actors have a direct interest in gaining such
knowledge including network equipment suppliers, network operators,
regulatory and local authorities. These processes and their effects vary
a lot across scales: although the diffusion of a new technology might
not be optimal at a local level, it might be beneficial from a global
perspective as it could lead to faster diffusion to less advantaged
places [@leibowicz2016representing]. Despite the spatial heterogeneity
of such diffusion mechanisms and the policy relevance, there is a
scarcity of studies analysing the diffusion of new technologies
at a detailed geographical level because of the lack of detailed enough
data and adequate research methods.

<!-- motivation: regional development -->
>This gap becomes even more prominent if we consider the importance of
technology and its adoption in economic geography and macroeconomic
growth theories. Simply put, differences in technological adoption and
sophistication may lead to uneven development as new technologies can
increase productivity and allow firms to introduce new products
[@solow1957technical; @aghion1990model; @kemeny2011international].
Linked to the subject of this paper, the Web and, more specifically, 
commercial websites can be considered as the underpinning
technology for the transformative process identified by
@capello2024nexus as the *digital service economy*. Importantly, the
focus here is not the Web in general, but instead commercial websites.
After all, diffusion together with invention and innovation are
considered the pillars of technological change [@das2022diffusion].
Findings from previous studies illustrated that early engagement with
digital technologies such as the Web led to longstanding positive
productivity gains for these regions that hosted early adopters
[@tranosuk]. Hence, obtaining a robust understanding of the spatial
diffusion mechanisms is crucial in mapping future development trajectories.

<!-- NEW motivation: intangible/digital -->
> Another line of motivation has to do with the very nature of the Web as a 
digital technology and how it evolved over time. The digital geographies field 
has debunked premature claims about the Internet's placeless-ness by mapping 
various of its facets and technological layers [@tranos2013death], but the lack 
of relevant long time-series data prevented researchers from observing digital
phenomena overtime. Most of these studies focused on its hard infrastructure 
[e.g. @malecki2002economic; @moss2000internet], on Internet subscribers 
[e.g. @blank2018local], or on social media users [e.g. @crampton2013beyond].
Exceptions include early work from @zook2000web, @zook2000web and 
@moss1997tracking, which utilised domain name registration data and use it to
map and illustrate the spatial footprint of the web content. Pivotal as these 
contributions have been in understanding the economic geographies of the 
Internet, they were based on cross-sectional, often spatially detailed, mapping 
and on short temporal comparisons (e.g. 1993-1998) and did not observe the 
evolution and diffusion of the Web until its maturity. As we know from the 
relevant literature, different technologies diffuse at different rates and 
there is no theory that can explain these differences 
[@leibowicz2016representing]. Hence, mapping and modelling the diffusion of the
Web can offer useful insights.

\color{red}
Reply: Ok, I understand these points and especially appreciate the praxis-oriented motivation.
What is still a bit thin is why insights from previous studies (which are limited) are not enough
and require an updated study at a finer granular level (this is the same as the previous point, so
the two can be combined.
\color{blue}

See response below.

\color{teal}
\noindent 2. Knowledge Gaps: The current review does not clearly identify the knowledge gaps that this study aims to address. Clarify whether the goal is to confirm known processes with new data and methods or to explore unique diffusion patterns related to websites.
\color{black}

The knowledge gaps have been explicitly highlighted in the restructured 
literature review section. For instance: 

> Although the above processes have been studied in innovation studies, the distancing of economic geographers from research questions about the diffusion of new technologies and innovations resulted to a knowledge gap regarding the explanatory power of these mechanisms at granular, local scales [@ding2010modeling].

> Although the early adoption and leapfrogging literature has not paid much attention on cities and regions [@yu2018sustainability], the potential local economic benefits justify the need to investigate the dynamics of the web diffusion in different scales
in the UK. Hence, the second empirical hypothesis states:

\color{red}
Reply: Please see my previous points concerning the motivation. While this is a valid argument,
I still miss a strong claim as to why existing studies leave a knowledge gap and why filling this
gap matters.
\color{blue}

See response below.

\color{teal}
\noindent 2. Geographical Scale: While the effort to model diffusion curves at a fine geographical scale is commendable, the paper does not sufficiently explain the benefits or additional knowledge gained from this approach.
\color{black}

A new figure (Figure 3) and the following text have been added to address this
point.

> What escaped from previous studies was εexploring whether such a pattern also 
describes cumulative adoption of new technologies at sub-national scales. To 
test this, the same  logistic function is estimated for each of the 374 LAD. The
detailed results are presented in Table \ref{table.s.lads} in the Appendix. 
The key finding is that for 342 LAD (91% of all LAD) the $R^2 > 0.9$ for the 
logistic function, which indicates that even at local scale the cumulative 
adoption of the Web is characterised by a pattern similar to the one observed 
for countries. Graphically, all these LAD curves are plotted in Figure 
\ref{s_lad_uk}. The different colour lines illustrate whether a LAD reached $t_0$ 
faster or slower than the UK in total. This heterogeneity is further discussed 
later in this section.

> This is the first time that such cumulative adoption curves have been estimated
for areal units as small as the UK LAD. Understanding and modelling the dynamics
of technological diffusion and, ultimately, being able to predict diffusion 
rates at such small local scales can directly support the deployment of 
infrastructural networks (e.g. 5G) and local technology policies. The above are 
in line with previous studies exploring the diffusion of web technologies 
[@PAPAGIANNIDIS2015308], social media [@lengyel2020role] and online
shopping [@bakher2013diffusion]. 

\color{red}
Reply: Ok, that is interesting and relevant and can be partially used to address my comment about the
motivation of the study. Yet, what is still not perfectly clear to me is whether the similarity of the
findings at the finer spatial level is to be expected or if there are theoretical reasons to expect otherwise.
In my eyes, using such a fine granular scale is the central (but not only) contribution of the paper.
Motivating it better, i.e., why it matters from a theoretical point and understanding of diffusion patterns,
can elevate the paper’s value. Put differently, are the diffusion mechanisms and drivers (spatially) scale
invariant? Discussing this briefly would greatly contribute to the paper’s message.
\color{blue}

I think all the above points can be addressed together, hence I am responding to 
them here. Indeed, there is a deeper theoretical justification for testing
how sensitive the diffusion mechanisms are to the geographical scale of observation 
and this is the Modifiable Unit Areal Problem. We know that various key theoretical concepts
in economic geography are sensitive to the spatial scale at which they are 
observed, but given the lack of previous studies, we do not know whether 
the diffusion mechanisms of a new technology are also sensitive to the spatial 
scale as well. The following paragraph has been added in the introduction.

> The lack of previous granular studies about the diffusion of new technologies 
deprives us from a reliable prior regarding whether the diffusion mechanisms 
and drivers are sensitive or not to the spatial scale that the diffusion of a 
new technology is observed. As per other key concepts in economic geography
[@briant2010dots; @meliciani2015determinants; @andini2019social; @rosenthal2001determinants],
diffusion mechanisms can indeed suffer from Modifiable Areal Unit Problem 
(MAUP): although the adoption of a new technology is at its core an individual 
process, it is hardly ever observed at this, or at a close enough, scale. 

---

\color{teal}
\noindent 3. Lack of Hypotheses: To clarify what the paper delivers and what knowledge gaps it fills, I strongly recommend developing a number of hypotheses that will be tested.
\color{black}

The following two hypotheses have been added and the whole paper is now 
structured around them:

> H~1~: The three diffusion mechanisms namely distance, urban hierarchy
and the S-shaped pattern of the cumulative level of adoption shaped
the diffusion of the commercial Web in the UK even at granular geographical 
scales.

> H~2~: The diffusion of the commercial Web is shaped by both early adoption 
and latecomer effects.

\color{red}
Reply: I do wonder a bit what the alternatives are. I mean, what factors other than the ones named in
the hypothesis can be expected to share the diffusion? Please clarify in the text leading to the
hypotheses, explaining why these factors can be expected to be dominant.
\color{blue}

The below sentence has been added after the description of the three mechanisms:

> The diffusion of new technologies and innovations is driven by three
different mechanisms [@grubler1990rise; @morrill2020spatial]: (i)
distance and proximity, (ii) urban hierarchies in the form of a
centrifugal forces as new technologies diffuse from core to periphery,
and (iii) over time the cumulative level of adoption follows an S-shaped
pattern.
<!-- R2 addition -->
Although some studies focused on other, case-specific drivers -- for example 
@lengyel2020role on urban scaling and @bednarz2020pulled on regional demand --
the literature is in agreement that these are the three fundamental diffusion 
mechanisms. 

\color{teal}
\noindent 5. Retail Centers: The sudden shift to retail centers on page 15 is confusing, given that the data pertains to all commercial sites. Clarify the rationale for this focus.
\color{black}

The retail centres discussion has now been moved in the methods sections, so it
appears much earlier in the paper. In addition, the following text has been 
modified in the relevant paragraph:

> To capture the hierarchical mechanism the model includes as predictors a
one year lag of website density in London, the largest city in the UK, and a
one year lag of the website density in the nearest city. Both variables clearly
illustrate the urban hierarchy in the UK. Especially for the OA models, a 
third predictor is added to capture hierarchy at a much more granular scale:
a one year lag of the website density in the the nearest retail centre [^4]. As
the literature illustrates, retail centres are key components of urban systems
[@dennis2002central, @jones2021reframing]. Due to the small sizes of the retail 
centres, the latter is only relevant for and included in the OA models and not 
in the LAD models.

> [^4]: The retail centres data have been obtained by the Consumer Data Research Centre, an ESRC data investment, under project ID CDRC 498-01, ES/L011840/1; ES/L011891/1: <https://data.cdrc.ac.uk/dataset/retail-centre-boundaries-and-open-indicators>.

\color{red}
Reply: Ok. I would suggest refining the text a bit to make clear that this is an illustration of a specific
empirical case, i.e., the consideration of an additional factor, as an illustration of the robustness of the
results as well as potential adaptability of the empirical model to consider more factors in other
circumstances.
\color{blue}

The below sentence has been added in the above paragraph:

> By including this predictor, the model is better tuned towards the spatial 
characteristic of the OA scale. Hence, it increases the robustness of the model.

\color{black}

## References