---
title: "diffusion, websites with 1 pc"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output: 
  html_document:
    df_print: paged
    toc: true
    toc_float: true
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output")
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rprojroot)
library(rgdal)
library(spdep)
library(sppt)
library(spatstat)

options(scipen=10000)

# This is the project path
path <- find_rstudio_root_file()
```

Postcode lookup.

[source](https://geoportal.statistics.gov.uk/datasets/postcode-to-output-area-to-lower-layer-super-output-area-to-middle-layer-super-output-area-to-local-authority-district-august-2021-lookup-in-the-uk/about)

```{r}
path.lookup <- paste0(path,"/data/raw/PCD_OA_LSOA_MSOA_LAD_AUG21_UK_LU.csv")
lookup <- read_csv(path.lookup) %>% 
  select(pcds, msoa11cd, dointr, doterm) %>% 
  dplyr::rename(pc = pcds)
#glimpse(lookup)
# The problems refer to Welsh LAD names. Not a problem for the analysis.
#sapply(lookup, function(x) sum(is.na(x)))
# 10332 missing msoa11cd

path.lookup <- "/hdd/internet_archive/archive/ONSPD_FEB_2017_UK.csv"
lookup <- read_csv(path.lookup) %>% 
  select(pcds, oseast1m, osnrth1m) %>% 
  dplyr::rename(pc = pcds)

```

The internet archive data is saved on /hdd.

```{r}
n = 1 #number of unique postcodes 

data.folder9610 <- "/hdd/internet_archive/archive/data/"
data.path9610 <- paste0(data.folder9610, "domain_pc_year.csv")
#Created by domain.R, which uses domain instead of host.
#This is what we use for the hyperlinks paper as per George's script

data.path1112 <- paste0(path, "/data/temp/domain_pc_year1112.csv")
#Created by domain1112.Rmd, which is based on domain.R and uses domain instead of host.
#This is what we use for the hyperlinks paper as per George's script

df9610 <- read_csv(data.path9610) 
df1112 <- read_csv(data.path1112)

df <- bind_rows(df9610, df1112) %>% 
  filter(V1.domain == n,
         year > 1995) %>% 
  left_join(lookup, by = "pc", suffix =c("","")) 

rm(df9610, df1112)
```

## Boundary data

```{r}
# get GB
path.gb <- paste0(path, "/data/raw/Countries_(December_2020)_UK_BUC.geojson")
gb <- readOGR(path.gb) 
# spatial transformations
gb <- spTransform(gb, CRS("+init=epsg:4326"))
gb <- subset(gb, CTRY20NM != "Northern Ireland")
gb.df <- fortify(gb, region = "CTRY20NM")

# get MSOA 
# source: https://geoportal.statistics.gov.uk/datasets/middle-layer-super-output-areas-december-2011-boundaries-generalised-clipped-bgc-ew-v3/explore?location=52.849644%2C-2.489527%2C7.08

path.geo <- paste0(path, "/data/raw/Middle_Layer_Super_Output_Areas_(December_2011)_Boundaries_Generalised_Clipped_(BGC)_EW_V3.geojson")
msoa <- readOGR(path.geo)
# UK BFC: la <- readOGR("https://opendata.arcgis.com/datasets/1d78d47c87df4212b79fe2323aae8e08_0.geojson") 
# source: https://data.gov.uk/dataset/7c387c64-d25f-474a-b07e-b933578caea2/local-authority-districts-april-2019-boundaries-uk-bfe

# cities
cities <- maps::world.cities %>% 
  filter(country.etc=="UK") %>% 
  arrange(pop) %>% tail(10) 
tif_sf <- st_as_sf(cities, coords = c("long", "lat"), crs = 4326)

# get OA for England and Wales
path.geo <- paste0(path, "/data/raw/Output_Areas__December_2011__Boundaries_EW_BGC.geojson")
oa.ew <- readOGR(path.geo)
# source: https://geoportal.statistics.gov.uk/

# spatial transformations
oa.ew <- spTransform(oa.ew, CRS("+init=epsg:4326"))

# keep in the data slot only the ONS Output Area id, renaming it as 'id'
oa.ew <- oa.ew[, 'OA11CD']
colnames(oa.ew@data) <- c('id')

# reassign the polygon IDs
oa.ew <- spChFIDs(oa.ew, as.character(oa.ew$id))

# check the CRS has changed correctly, and the data slot has shrink to only the ID
summary(oa.ew)

# # get OA for Scotland
path.geo.sc <- paste0(path, "/data/raw/output-area-2011-mhw")
oa.sc <- readOGR(dsn=path.geo.sc, layer = "OutputArea2011_MHW")
# source: https://www.nrscotland.gov.uk/statistics-and-data/geography/our-products/census-datasets/2011-census/2011-boundaries

# spatial transformations
oa.sc <- spTransform(oa.sc, CRS("+init=epsg:4326"))

# Scotland (follows same steps as EW, see notes above)
oa.sc <- oa.sc[, 'code']
colnames(oa.sc@data) <- c('id')

# reassign the polygon IDs
oa.sc <- spChFIDs(oa.sc, as.character(oa.sc$id))

# check the CRS has changed correctly, and the data slot has shrink to only the ID
summary(oa.sc)

# build oa for GB
oa.gb <- spRbind(oa.ew, oa.sc)
rm(oa.ew, oa.sc)


```

## sppt

```{r}

gb <- spTransform(gb, CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
msoa <- spTransform(msoa, CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
oa.gb <- spTransform(oa.gb, CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))

results.1 <- data.frame()
results.2 <- data.frame()

for (t in 1996:2012){
  a <- df %>%
    #slice_sample(n = 10000) %>% 
    filter(!is.na(oseast1m), #6k rows with missing east/north for all years
           year == t,
           substr(pc, 1,2) !="BT") %>% #drop Northern Ireland, for 2010 c. 4k obs.
    st_as_sf(coords = c("oseast1m", "osnrth1m"), crs = 27700) %>%
    st_transform(4326) %>%
    st_coordinates() %>%
    as_tibble() %>%
    st_as_sf(coords = c("X", "Y"),
                        crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0") %>% 
  as("Spatial")
  
  b <- df %>%
    #slice_sample(n = 10000) %>% 
    filter(!is.na(oseast1m), #6k rows with missing east/north for all years
           year == t+1,
           substr(pc, 1,2) !="BT") %>% #drop Northern Ireland, for 2010 c. 4k obs.
    st_as_sf(coords = c("oseast1m", "osnrth1m"), crs = 27700) %>%
    st_transform(4326) %>%
    st_coordinates() %>%
    as_tibble() %>%
    st_as_sf(coords = c("X", "Y"),
                        crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0") %>% 
    as("Spatial")
  
  a <- spTransform(a, CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
  b <- spTransform(b, CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
  
  a@data <- a@data %>% mutate(id = 1:nrow(a@data))
  b@data <- b@data %>% mutate(id = 1:nrow(b@data))
  
  set.seed(93255) # set seed for reproducibility
  #output <- sppt(sp1998, sp1999, msoa)
  #output@data

  #output2 <- sppt_boot(sp1998, sp1999, msoa)
  #output2@data

  #output3 <- sppt_diff(sp1998, sp1999, msoa)
  #output3@data

  output.oa <- sppt(a, b, oa.gb)
  #output.oa@data
  results.1 <- summary_sppt(output.oa) %>% as_tibble() %>%
    mutate(year = t) %>% 
    bind_rows(results.1)

  output.oa2 <- sppt_boot(a, b, oa.gb)
  #output.oa2@data 
  results.2 <- summary_sppt(output.oa2) %>% as_tibble() %>% 
    mutate(year = t) %>% 
    bind_rows(results.2)

  #output.oa3 <- sppt_diff(a, b, oa.gb)
  #output.oa3@data
}

out.path1 <- paste0(path, "/outputs/sppt_oa.csv")
out.path2 <- paste0(path, "/outputs/sppt_boot_oa.csv")
write_csv(results.1, out.path1)
write_csv(results.2, out.path2)

```

## Kernel density estimation

```{r}
xy <- df %>%
    #slice_sample(n = 10000) %>% 
    filter(!is.na(oseast1m), #6k rows with missing east/north for all years
           year == 2010,
           substr(pc, 1,2) !="BT") %>% #drop Northern Ireland, for 2010 c. 4k obs.
    st_as_sf(coords = c("oseast1m", "osnrth1m"), crs = 27700) %>%
    st_transform(27700) %>%
    st_coordinates() %>%
    as_tibble() 

gb <- st_as_sf(gb, coords = c("oseast1m", "osnrth1m"), crs = 27700) 
gb <- st_transform(gb, 27700)
gb.win <- as.owin(gb)    
xy.ppp <- ppp(x=xy$X, y = xy$Y, window = gb.win)

  
plot(density(xy.ppp, sigma = 1000))
```


